# fly.toml app configuration file generated for jednickahk on 2024-04-02T22:24:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jednickahk'
primary_region = 'waw'

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[build.args]
  PB_VERSION="0.22.7"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'